# Generated by Django 4.1.4 on 2023-01-10 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Animals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('age', models.FloatField()),
                ('adopted', models.BooleanField(default=False)),
                ('breed', models.CharField(max_length=100)),
            ],
        ),
    ]
