# Generated by Django 4.1 on 2023-01-10 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animal_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animals',
            name='age',
            field=models.FloatField(),
        ),
    ]
