# Generated by Django 4.1.4 on 2023-01-10 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animal_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnimalShelter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('street', models.CharField(max_length=100)),
                ('number', models.FloatField()),
                ('postal_code', models.FloatField()),
                ('province', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='animals',
            name='exotic',
            field=models.BooleanField(default=False),
        ),
    ]
