# Generated by Django 4.1 on 2023-01-10 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animal_app', '0002_alter_animals_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animals',
            name='age',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='person',
            name='age',
            field=models.IntegerField(max_length=3),
        ),
        migrations.AlterField(
            model_name='person',
            name='dni',
            field=models.IntegerField(max_length=15),
        ),
    ]
