# Generated by Django 4.1.4 on 2023-01-10 18:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('animal_app', '0003_person_animals_baby_animalshelter_contact_number_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='animalshelter',
            name='contact_number',
        ),
    ]
