# Generated by Django 4.1 on 2023-01-10 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animal_app', '0003_alter_animals_age_alter_person_age_alter_person_dni'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='age',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='person',
            name='dni',
            field=models.IntegerField(),
        ),
    ]
