# Generated by Django 4.1.4 on 2023-01-10 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animal_app', '0004_remove_animalshelter_contact_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='animalshelter',
            name='contact_number',
            field=models.FloatField(default='1112344321'),
        ),
    ]
