# Generated by Django 4.1.4 on 2023-01-10 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animal_app', '0004_alter_person_age_alter_person_dni'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person',
            old_name='house',
            new_name='house_type',
        ),
        migrations.AddField(
            model_name='animalshelter',
            name='shelter_type',
            field=models.CharField(default='Refugio', max_length=50),
            preserve_default=False,
        ),
    ]
