# Generated by Django 4.1.4 on 2023-01-10 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animal_app', '0005_rename_house_person_house_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animalshelter',
            name='number',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='animalshelter',
            name='postal_code',
            field=models.IntegerField(),
        ),
    ]
