# Generated by Django 4.1.4 on 2023-01-10 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animal_app', '0005_animalshelter_contact_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animalshelter',
            name='contact_number',
            field=models.FloatField(default=1112344321),
        ),
    ]
