# Generated by Django 4.1.4 on 2023-01-11 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animal_app', '0006_alter_animalshelter_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animals',
            name='adopted',
            field=models.BooleanField(default=True),
        ),
    ]
