# Generated by Django 4.1.4 on 2023-01-10 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animal_app', '0006_alter_animalshelter_contact_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animalshelter',
            name='contact_number',
            field=models.FloatField(),
        ),
    ]
