# Generated by Django 4.1.4 on 2023-01-13 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animal_app', '0007_alter_animals_adopted'),
    ]

    operations = [
        migrations.AddField(
            model_name='animals',
            name='gender',
            field=models.CharField(default='Hembra', max_length=100),
            preserve_default=False,
        ),
    ]
