# Generated by Django 4.1.4 on 2023-01-13 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animal_app', '0008_animals_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='contact_number',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
