# Generated by Django 4.1.4 on 2023-01-13 03:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('animal_app', '0010_contactnumber'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='contact_number',
        ),
    ]
