# Generated by Django 4.1.4 on 2023-02-08 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animal_app', '0012_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='animals',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='pets/'),
        ),
    ]
