# Generated by Django 4.1.4 on 2023-02-08 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animal_app', '0014_alter_animals_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animals',
            name='image',
            field=models.ImageField(default='media/pets/default.jpg', upload_to='pets/'),
        ),
    ]
