# Generated by Django 4.1.4 on 2023-02-08 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animal_app', '0017_alter_avatar_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='animalshelter',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='shelters/'),
        ),
    ]
