# Generated by Django 4.1.4 on 2023-02-08 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animal_app', '0019_userprofile_delete_person'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='contact_number',
            field=models.IntegerField(default=1100000000),
            preserve_default=False,
        ),
    ]
